location: gitman-repositories/
sources:
  - repo: https://github.com/letsencrypt/unbound_exporter.git
    name: unbound_exporter
    rev: main
    type: git
    params: --depth=1
    sparse_paths:
      -
    links:
      -
    scripts:
      -
sources_locked:
  - repo: https://github.com/letsencrypt/unbound_exporter.git
    name: unbound_exporter
    rev: 6f26d2555214b9b31fbffe522fcc46fc903b0f81
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -
default_group: ""
groups:
  -
