location: gitman-repositories/
sources:
  - repo: https://github.com/letsencrypt/unbound_exporter.git
    name: unbound_exporter
    rev: main
    type: git
    params: --depth=1
    sparse_paths:
      -
    links:
      -
    scripts:
      -
    patches:
      -
sources_locked:
  - repo: https://github.com/letsencrypt/unbound_exporter.git
    name: unbound_exporter
    rev: 01314cb6b51ed429f3e583d26b41d37754483084
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -
    patches:
      -
default_group: ""
groups:
  -
