location: gitman-repositories/
sources:
  - repo: https://github.com/letsencrypt/unbound_exporter.git
    name: unbound_exporter
    rev: main
    type: git
    params: --depth=1
    sparse_paths:
      -
    links:
      -
    scripts:
      -
sources_locked:
  - repo: https://github.com/letsencrypt/unbound_exporter.git
    name: unbound_exporter
    rev: 1209ca8fa675c6c307af0a2b04c6c0b8ac93edcf
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -
default_group: ""
groups:
  -
