location: gitman-repositories/
sources:
  - repo: https://github.com/letsencrypt/unbound_exporter.git
    name: unbound_exporter
    rev: main
    type: git
    params: --depth=1
    sparse_paths:
      -
    links:
      -
    scripts:
      -
sources_locked:
  - repo: https://github.com/letsencrypt/unbound_exporter.git
    name: unbound_exporter
    rev: d7fdac18edd21cb7e2fca5decacf7f1361ef8a87
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -
default_group: ""
groups:
  -
