x-definitions:
  common-service-options: &common-service-options
    restart: unless-stopped

services:
  app:
    <<: *common-service-options
    environment:
      MANAGE_HTTP_PORT: 80
      MANAGE_HTTPS_PORT: 443
      PORTAL_HTTP_PORT: 8080
      PORTAL_HTTPS_PORT: 8443
    ports:
      - ${DOCKER_COMPOSE_NETWORK_IP}:19810:19810/udp
      - ${DOCKER_COMPOSE_NETWORK_IP}:27001:27001/udp
      - ${DOCKER_COMPOSE_NETWORK_IP}:29810:29810/udp
      - ${DOCKER_COMPOSE_NETWORK_IP}:29811-29817:29811-29817

  certificator:
    <<: *common-service-options

  apache:
    <<: *common-service-options
    ports:
      - ${DOCKER_COMPOSE_NETWORK_IP}:80:80
      - ${DOCKER_COMPOSE_NETWORK_IP}:8080:8080
      - ${DOCKER_COMPOSE_NETWORK_IP}:443:443
      - ${DOCKER_COMPOSE_NETWORK_IP}:8443:8443

  apache-prometheus-exporter:
    <<: *common-service-options

  favicons:
    <<: *common-service-options
