servers:
  hosts:
    macbook-pro-2012:
      ansible_host: 10.1.4.101
      ansible_ssh_user: homelab
      ansible_shell_executable: /usr/bin/bash
    odroid-h3:
      ansible_host: 10.1.4.108
      ansible_ssh_user: homelab
      ansible_shell_executable: /usr/bin/bash
    raspberry-pi-4b-2g:
      ansible_host: 10.1.4.103
      ansible_ssh_user: homelab
      ansible_shell_executable: /usr/bin/bash
    raspberry-pi-4b-4g:
      ansible_host: 10.1.4.104
      ansible_ssh_user: homelab
      ansible_shell_executable: /usr/bin/bash
    odroid-h4-ultra:
      ansible_host: 10.1.4.111
      ansible_ssh_user: homelab
      ansible_shell_executable: /usr/bin/bash

empty:
  hosts:
