servers:
  hosts:
    macbook-pro-2012:
      ansible_host: 10.1.4.1
      ansible_shell_executable: /usr/bin/bash
    odroid-h3:
      ansible_host: 10.1.4.8
      ansible_shell_executable: /usr/bin/bash
    raspberry-pi-3b:
      ansible_host: 10.1.4.2
      ansible_shell_executable: /usr/bin/bash
    raspberry-pi-4b-2g:
      ansible_host: 10.1.4.3
      ansible_shell_executable: /usr/bin/bash
    raspberry-pi-4b-4g:
      ansible_host: 10.1.4.4
      ansible_shell_executable: /usr/bin/bash
    # raspberry-pi-zero-2w-1:
    #   ansible_host: 10.1.4.6
    #   ansible_shell_executable: /usr/bin/bash
    # raspberry-pi-zero-2w-2:
    #   ansible_host: 10.1.4.7
    #   ansible_shell_executable: /usr/bin/bash

empty:
  hosts:
