servers:
  hosts:
    odroid-h3:
      ansible_host: 10.1.4.1
      ansible_ssh_user: homelab
      ansible_shell_executable: /usr/bin/bash
    odroid-h4-ultra:
      ansible_host: 10.1.4.4
      ansible_ssh_user: homelab
      ansible_shell_executable: /usr/bin/bash
    raspberry-pi-4b-2g:
      ansible_host: 10.1.4.5
      ansible_ssh_user: homelab
      ansible_shell_executable: /usr/bin/bash
    raspberry-pi-4b-4g:
      ansible_host: 10.1.4.6
      ansible_ssh_user: homelab
      ansible_shell_executable: /usr/bin/bash
    macbook-pro-2012:
      ansible_host: 10.1.4.7
      ansible_ssh_user: homelab
      ansible_shell_executable: /usr/bin/bash

empty:
  hosts:
