apps:
  - url: dawarich.matejhome.com
    auth: basic
    path: /metrics
  - url: docker-stats-odroid-h3.matejhome.com
    auth: basic
    path: /metrics
  - url: docker-stats-odroid-h4-ultra.matejhome.com
    auth: basic
    path: /metrics
  - url: docker-stats-raspberry-pi-4b-2g.matejhome.com
    auth: basic
    path: /metrics
  - url: docker-stats-raspberry-pi-4b-4g.matejhome.com
    auth: basic
    path: /metrics
  - url: gatus-1.matejhome.com
    auth: basic
    path: /metrics
  - url: gatus-2.matejhome.com
    auth: basic
    path: /metrics
  - url: healthchecks.matejhome.com
    auth: bearer
    path: /projects/${HEALTHCHECKS__PROMETHEUS_PROJECT}/metrics
  - url: homeassistant.matejhome.com
    auth: bearer
    path: /api/prometheus
  - url: jellyfin.matejhome.com
    auth: basic
    path: /metrics
  - url: minio.matejhome.com
    auth: bearer
    path: /minio/v2/metrics/cluster
  - url: nodeexporter-odroid-h3.matejhome.com
    auth: basic
    path: /metrics
  - url: nodeexporter-odroid-h4-ultra.matejhome.com
    auth: basic
    path: /metrics
  - url: nodeexporter-raspberry-pi-4b-2g.matejhome.com
    auth: basic
    path: /metrics
  - url: nodeexporter-raspberry-pi-4b-4g.matejhome.com
    auth: basic
    path: /metrics
  - url: pihole-1-primary.matejhome.com
    auth: basic
    path: /metrics
  - url: pihole-1-secondary.matejhome.com
    auth: basic
    path: /metrics
  - url: pihole-2-primary.matejhome.com
    auth: basic
    path: /metrics
  - url: pihole-2-secondary.matejhome.com
    auth: basic
    path: /metrics
  - url: prometheus.matejhome.com
    auth: basic
    path: /metrics
  - url: uptimekuma-1.matejhome.com
    auth: basic
    path: /metrics
  - url: uptimekuma-2.matejhome.com
    auth: basic
    path: /metrics
  - url: unbound-1-default.matejhome.com
    auth: basic
    path: /metrics
  - url: unbound-1-matej.matejhome.com
    auth: basic
    path: /metrics
  - url: unbound-1-monika.matejhome.com
    auth: basic
    path: /metrics
  - url: unbound-1-iot.matejhome.com
    auth: basic
    path: /metrics
  - url: unbound-1-guests.matejhome.com
    auth: basic
    path: /metrics
  - url: unbound-2-default.matejhome.com
    auth: basic
    path: /metrics
  - url: unbound-2-matej.matejhome.com
    auth: basic
    path: /metrics
  - url: unbound-2-monika.matejhome.com
    auth: basic
    path: /metrics
  - url: unbound-2-iot.matejhome.com
    auth: basic
    path: /metrics
  - url: unbound-2-guests.matejhome.com
    auth: basic
    path: /metrics

proxies:
  - url: actualbudget.matejhome.com
  - url: certbot.matejhome.com
  - url: changedetection.matejhome.com
  - url: dawarich.matejhome.com
  - url: docker-cache-proxy-dockerhub.matejhome.com
  - url: docker-stats-odroid-h3.matejhome.com
  - url: docker-stats-odroid-h4-ultra.matejhome.com
  - url: docker-stats-raspberry-pi-4b-2g.matejhome.com
  - url: docker-stats-raspberry-pi-4b-4g.matejhome.com
  - url: dozzle.matejhome.com
  - url: gatus-1.matejhome.com
  - url: gatus-2.matejhome.com
  - url: gotify.matejhome.com
  - url: grafana.matejhome.com
  - url: groceries.matejhome.com
  - url: healthchecks.matejhome.com
  - url: homeassistant.matejhome.com
  - url: homepage.matejhome.com
  - url: jellyfin.matejhome.com
  - url: minio-console.matejhome.com
  - url: minio.matejhome.com
  - url: motioneye-kitchen.matejhome.com
  - url: nodeexporter-odroid-h3.matejhome.com
  - url: nodeexporter-odroid-h4-ultra.matejhome.com
  - url: nodeexporter-raspberry-pi-4b-2g.matejhome.com
  - url: nodeexporter-raspberry-pi-4b-4g.matejhome.com
  - url: ntfy.matejhome.com
  - url: ollama.matejhome.com
  # - url: ollama-private.matejhome.com
  - url: omadacontroller.matejhome.com
  - url: openspeedtest.matejhome.com
  - url: openwebui.matejhome.com
  # - url: openwebui-private.matejhome.com
  - url: pihole-1-primary.matejhome.com
  - url: pihole-1-secondary.matejhome.com
  - url: pihole-2-primary.matejhome.com
  - url: pihole-2-secondary.matejhome.com
  - url: prometheus.matejhome.com
  - url: renovatebot.matejhome.com
  - url: smtp4dev.matejhome.com
  - url: tvheadend.matejhome.com
  - url: unbound-1-default.matejhome.com
  - url: unbound-1-matej.matejhome.com
  - url: unbound-1-monika.matejhome.com
  - url: unbound-1-iot.matejhome.com
  - url: unbound-1-guests.matejhome.com
  - url: unbound-2-default.matejhome.com
  - url: unbound-2-matej.matejhome.com
  - url: unbound-2-monika.matejhome.com
  - url: unbound-2-iot.matejhome.com
  - url: unbound-2-guests.matejhome.com
  - url: unificontroller.matejhome.com
  - url: uptimekuma-1.matejhome.com
  - url: uptimekuma-2.matejhome.com
  - url: vaultwarden.matejhome.com
  - url: wikipedia.matejhome.com
  - url: wiktionary.matejhome.com
