basic_auth_users:
  matej: ${PROMETHEUS__MATEJ_PASSWORD_ENCRYPTED}
  homelab-viewer: ${PROMETHEUS__HOMELAB_VIEWER_PASSWORD_ENCRYPTED}
  homelab-test: ${PROMETHEUS__HOMELAB_TEST_PASSWORD_ENCRYPTED}
  prometheus: ${PROMETHEUS__PROMETHEUS_PASSWORD_ENCRYPTED}
