location: gitman-repositories/
sources:
  - repo: https://github.com/imker25/samba_exporter.git
    name: samba_exporter
    rev: main
    type: git
    params: --depth=1
    sparse_paths:
      -
    links:
      -
    scripts:
      -
sources_locked:
  - repo: https://github.com/imker25/samba_exporter.git
    name: samba_exporter
    rev: 51a0efeec99ed6d75af51a2fbb5180e2d1c6d56d
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -
default_group: ""
groups:
  -
