services:
  app:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: app
    build:
      dockerfile: ./external/unifi-network-application/Dockerfile
    init: false
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_HOST: mongodb
    volumes:
      - ./app-data/unifi-network-application:/config:rw
      - ./app-secrets/mongodb-password.txt:/homelab/mongodb-password.txt:ro
    dns: # Use blackhole DNS
      - 10.1.12.6
      - 10.1.10.6
    networks:
      internal-network: {}
      external-network: {}
    stop_grace_period: 30s
    tmpfs:
      - /defaults:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
      - /run:rw,exec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}

  mongodb:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: app
    container_name: ${DOCKER_COMPOSE_APP_NAME}-mongodb
    build:
      dockerfile: ./external/mongodb/Dockerfile
    environment:
      MONGO_AUTHSOURCE: admin
      MONGO_DBNAME: unifi
      MONGO_USER: unifi
    env_file:
      - ./app-secrets/mongodb.env
    volumes:
      - ./app-data/mongodb:/data/db:rw
      - ../../../../docker-images/external/unifi-network-application/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

  certificator:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: certificator

  apache:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache

  apache-prometheus-exporter:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache-prometheus-exporter

  favicons:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: favicons

  # web-backup:
  #   extends:
  #     file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
  #     service: template
  #   container_name: ${DOCKER_COMPOSE_APP_NAME}-web-backup
  #   build:
  #     dockerfile: ./custom/web-automation/Dockerfile
  #   depends_on:
  #     app:
  #       condition: service_healthy
  #   env_file:
  #     - ./app-secrets/web-backup.env
  #   environment:
  #     HOMELAB_CONTAINER_VARIANT: backup
  #   volumes:
  #     - ./app-data/web-backup:/homelab/backup:rw
  #     - ./app-logs/web-backup-errors:/homelab/errors:rw
  #     - ./app-logs/web-backup:/homelab/logs:rw

networks:
  default:
    driver: none
  internal-network:
    name: ${DOCKER_COMPOSE_APP_NAME}-internal-network
    driver: bridge
    internal: true
  external-network:
    name: ${DOCKER_COMPOSE_APP_NAME}-external-network
    driver: bridge
    internal: false
