name: Deploy

permissions: {}

on:
  pull_request:

jobs:
  deploy:
    name: Deploy - ${{ matrix.server }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        server:
          - macbook-pro-2012
          - odroid-h3
          - odroid-h4-ultra
          - raspberry-pi-4b-2g
          - raspberry-pi-4b-4g
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3.7.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: 3.x

      - name: Setup NodeJS
        uses: actions/setup-node@v6.0.0
        with:
          node-version: latest

      - name: Install system dependencies
        run: |
          set -euf
          sudo apt-get install --yes --no-install-recommends apache2-utils moreutils
          npm install -g @go-task/cli

      - name: Prepare secrets
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        working-directory: ./servers/${{ matrix.server }}
        run: task secrets -- --mode dev --offline

      # - name: Build apps
      #   working-directory: ./servers/${{ matrix.server }}
      #   run: task build -- --mode dev --dry-run

      - name: Run apps
        working-directory: ./servers/${{ matrix.server }}
        run: task start -- --mode dev --dry-run
